### PR TITLE
ROB-09238: Stepper Motor with Cable added

### PR DESCRIPTION
**Pull request by AMagill**

### CODE REVIEW

**Comment by zinefer** [comment]
Great work!

I plan to get some tools added to this repository to so that we can quickly check these models with the SFE viewer locally. Please bear with me for now as I will need to check these by hand.

**Comment by AMagill** [comment]
Thanks!  If you need any changes, let me know.
That would be great- the JSON output is the only part I wasn't able to double-check with materials and everything.  A standalone viewer HTML would be nice, especially if it didn't need a web server.,

**Comment by zinefer** [comment]
Sorry it took me so long to get back to this. I've had a lot to work on lately.

I've added an html template that can be used to preview display models with our viewer. Unfortunately, short of rewriting the viewer as a chrome extension, there was no real way to remove the need for a web server.

As for your models, it appears that you have some sort of smoothing option set. Maybe UVs?
image

**Comment by mgrusin** [comment]
Don't know if it applies here, but in the software I use (Lightwave), that's an shading artifact of having a contiguous mesh on the whole model, when what you really want is for the mesh to be discontiguous at sharp corners (box edges etc.). Cutting and repasting flat surfaces (e.g. the top of the motor) adds new edges that fix this. Or you can turn off smooth shading.

**Comment by AMagill** [comment]
That looks like bad normals to me.  Maybe I exported averaged vertex normals instead of face normals.  I also notice that none of the other .json files in the repo include normals at all- I guess three.js must automatically try to compute them itself when they're not provided.  (I do work with WebGL, but I mostly avoid three.js.)  I'll have to experiment with fixing this later.

One approach to making the preview html serverless would be to hook up an <input type="file"> or a dropzone to a FileReader ([like so](http://www.html5rocks.com/en/tutorials/file/dndfiles/)), read the file, and then hand over that string to DDD.  Sfe.js looks at first glance like it would just need a few lines of code to be able to accept a json string rather than a URL.

**Comment by zinefer** [comment]
Are you working directly with WebGL or is there another renderer that I am unaware of?

You are right that we have not been including normals ... I'm not sure what threejs is doing but we haven't had any real issues. 

A ```FileReader``` would not work for models with textures.

**Comment by zinefer** [comment]
You were correct. Exporting your blend file without normals fixed the issue. 

There is this small face that looks unintentional:
image

If you'd like me to commit a fixed json and merge this PR then let me know.

**Comment by AMagill** [comment]
Directly with WebGL.  [Check it out!](http://ominoushum.com/gl/)  I guess I don't like being sheltered from technical details.  I'll take bare metal programming on an MSP430 or an ARM Cortex over an Arduino any day.  :)

That's a good point about the textures.  I hadn't thought of that.  Perhaps it can be made to work out of Github, with something like [RawGit](https://rawgit.com/)?

Cool!  Glad it works.  If there's nothing you really want me to go back and fix (like that one face- probably just fix its material assignment), I'm cool with you just checking yours.

**Comment by zinefer** [comment]
Your work is really impressive. I added a shader to the sparkfun viewer and it wasn't very easy.

Sorry it's taken me so long to get this merged. I promise the next PR will be merged much quicker. :)

**Pull request merged**
